french_fries = input (" What is your favorite animal?\n")
hamster = input ("Why do you like them?\n")
user_input3 = input ( "where do they live?\n")
user_input4 = input ("What is a fun fact about Them?\n")
user_input5 = input ("What color are they?\n")
print("your favorite animal is the " + french_fries + "because" + hamster + "." + "they live in " + user_input3 + "and" + user_input4 + "they are" + user_input5)